### ISSUE TITLE
Logo Design For PinSafe Resolver

### ISSUE THREAD

**Issue by zularizal** [fragonib/pinsafe-resolver#1]
Hi @fragonib , I'm a graphic designer. Your project looks interesting, but the logo looks simple and less attractive.

That's why I want to contribute to this project by creating a new logo / icon for free. What do you think?

**Comment by fragonib** [comment]
Hi @zularizal. 

Thank you for your offer. You're right, current logo is quite simple and autogenerated from text. Project purpose is to be opensourced, and to resolve automatically VPN security throught PINsafe SMS, like one provided from some vendors as Pulse Secure Network Connect (TM). If you consider to contribute to the project I'll remove current logo and change it with new logo you provide as far as it be related enought with project goals.

**Comment by zularizal** [comment]
Yes @fragonib , I want to contribute to this project. Give me time, I will design the logo for this project.
I will send the logo proposal in the next reply.

**Comment by zularizal** [comment]
Hi @fragonib , these are design logos for your project. These logos are inspired by shield, password and network.

What do you think? Which do you like? If there is something you want to change, let me know.

![logo](https://user-images.githubusercontent.com/38547278/53395733-239fc000-39d5-11e9-9e41-9361a57cb560.png)

**Comment by fragonib** [comment]
Hi @zularizal. Thank you for your work. I'm sorry for late answer. 

Nice work, perhaps you can improve your current job adding something that represents multifactor authentication (maybe adding a mobile icon?). Or may be you can to you logo a 'PINsafe' text. This way your icon can tell the app apart from others than manage pins but they has other goals. I'm not a designer so your ideas are welcomed.

Please consider your final job has to be published with a free license (maybe creative commons)

**Comment by zularizal** [comment]
Okay, I chose to replace the star object into the text "PINsafe". What do you think?

And the logo is published with a free (Creative Commons) license.

If there are no changes, I will send the pr.
![bitmap](https://user-images.githubusercontent.com/38547278/53567660-7d011e00-3b92-11e9-8d82-8770c1905b36.png)

**Comment by fragonib** [comment]
Sorry, I stopped spending time on the project. Thank you very much for your contribution.
